# Generated by Django 5.2.15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=64, unique=True)),
                ("user_name", models.CharField(max_length=50)),
                (
                    "total_credits",
                    models.DecimalField(decimal_places=5, default=0, max_digits=18),
                ),
                (
                    "total_debits",
                    models.DecimalField(decimal_places=5, default=0, max_digits=18),
                ),
                ("transaction_count", models.IntegerField(default=0)),
                (
                    "net_balance",
                    models.DecimalField(decimal_places=5, default=0, max_digits=18),
                ),
                ("rank_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["-rank_score"], name="Home_user_rank_sc_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")],
                        max_length=6,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "descriptions",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="Home.user",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="Home_transa_user_id_idx",
                    )
                ],
                "unique_together": {("user", "idempotency_key")},
            },
        ),
    ]
